### ISSUE TITLE
Line

### ISSUE THREAD

**Issue by DeRobyJ** [rbiondo90/IngInfUnipa-Java2016-17-Esercitazioni#3]
Domandona, perchè in es03 per creare una linea "valida" dovrei avere un punto all'origine?
Che intendi per validity?

**Comment by rbiondo90** [comment]
Era una delle condizioni di valutazione (errate) che avevo imposto nella versione precedente. Ho sistemato sia questa che quella del piano nella nuova revisione. Praticamente avevo fatto confusione trattando i punti come vettori.
